- name: Install arch dependencies
  become: yes
  ansible.builtin.package:
    name:
      - iwd
      - polybar
      - xmonad
      - xmonad-contrib
      - picom
      - flameshot
      - feh
      - ffmpeg
      - nemo
      - greetd
      - tuigreet
    state: present
- name: Symlink X11
  file:
    src: '{{ ansible_env.HOME }}/dotfiles/.xinitrc'
    dest: '{{ ansible_env.HOME }}/.xinitrc'
    state: link
- name: Symlink picom
  file:
    src: '{{ ansible_env.HOME }}/dotfiles/picom'
    dest: '{{ ansible_env.HOME }}/.config/picom'
    state: link
- name: Symlink Xmonad
  file:
    src: '{{ ansible_env.HOME }}/dotfiles/xmonad'
    dest: '{{ ansible_env.HOME }}/.xmonad'
    state: link
- name: Symlink lf
  file:
    src: '{{ ansible_env.HOME }}/dotfiles/lf'
    dest: '{{ ansible_env.HOME }}/.config/lf'
    state: link
- name: Symlink greetd
  become: yes
  file:
    src: '{{ ansible_env.HOME }}/dotfiles/greetd'
    dest: '/etc/greetd'
    state: link
